stages:
  - test

test_job:
  stage: test
  tags:
    - linux
  script:
    - chmod -R 777 /var/lib/apt/
    - apt-get update -y
    - apt-get install -y python3
    - pip install -r requirements.txt 
    - ./app_unittest.py
