stages:
 - test
 - scan

test_job:
  stage: test
  tags:
    - linux
  script:
    - rm -rf __pycache__
    - touch coverage.xml
    - docker build -t local:testchat .
    - docker run -v ${PWD}:/opt/pwd local:testchat
  artifacts:
    paths:
      - coverage.xml
  variables:
    GIT_STRATEGY: clone

scan_job:
  stage: scan
  tags:
    - linux
  script:
    - rm -rf __pycache__
    - docker run -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli
  dependencies:
    - test_job
  variables:
    GIT_STRATEGY: clone

