stages:
  - test

test_job:
  stage: test
  tags:
    - linux
  script:
    - chmod -R 777 /var/lib/apt/||true
    - apt-get update -y||true
    - apt-get install -y python3||true
    - pip install -r requirements.txt||true
    - ./app_unittest.py
