stages:
#  - test
 - scan

test_job:
  stage: test
  tags:
    - linux
  script:
    - python3 -m venv ~/.py3flask
    - . ~/.py3flask/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - ./app_unittest.py

scan_job:
  stage: scan
  tags:
    - linux
  image: sonarsource/sonar-scanner-cli
