stages:
#  - test
 - scan

#test_job:
#  stage: test
#  tags:
#    - linux
#  script:
#    - python3 -m venv ~/.py3flask
#    - . ~/.py3flask/bin/activate
#    - pip install --upgrade pip
#    - pip install -r requirements.txt
#    - ./app_unittest.py

scan_job:
  stage: scan
  tags:
    - linux
  image: sonarsource/sonar-scanner-cli
  variables:
    SONAR_TOKEN: sqp_1220f7cfc2bd3dfdffbcb884da7e8f13f70dde38
    SONAR_HOST_URL: https://sonarqube.ellisbs.co.uk
  script:
    - find / 2>/dev/null
    - /opt/sonar-scanner/bin/sonar-scanner
